id: A3F07DE04
title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great Master
  Padmasambhava'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:20:41.688540
  last_modified_at: 2022-03-01 02:20:41.688544
