id: A3F07DE04
title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:20:41.693374
  last_modified_at: 2022-03-01 02:20:41.693378
