id: A3F07DE04
title: A Praise to the Lotus King
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:20:41.684288
  last_modified_at: 2022-03-01 02:20:41.684295
